config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "events#index"

  resources :events do
    resources :comments, only: %i[create destroy]
    resources :subscriptions, only: %i[create destroy]
    resources :photos, only: %i[create destroy]
    put :update_photo, on: :member
    post :show, on: :member
  end

  resources :users, only: %i[show edit update]
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user

  has_many :comments, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :subscribers, through: :subscriptions, source: :user
  has_many :photos, dependent: :destroy

  validates :user, presence: true
  validates :title, presence: true, length: { maximum: 255 }
  validates :address, presence: true
  validates :datetime, presence: true

  def visitors
    (subscribers + [user]).uniq
  end

  def pincode_valid?(pin2chek)
    pincode == pin2chek
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[show index]

  after_action :verify_policy_scoped, only: :index
  after_action :verify_authorized, except: %i[index]

  def index
    @events = policy_scope(Event)
  end

  def show
    pincode = params[:pincode] || cookies.permanent["events_#{@event.id}_pincode"]

    event_context = EventContext.new(event: @event, pincode: pincode)
    authorize event_context, policy_class: EventPolicy

    cookies.permanent["events_#{@event.id}_pincode"] = pincode

    @new_comment = @event.comments.build(params[:comment])
    @new_subscription = @event.subscriptions.build(params[:subscription])
    @new_photo = @event.photos.build(params[:photo])
  rescue Pundit::NotAuthorizedError
    render_password_form
  end

  def edit
    authorize @event
  end

  def new
    @event = current_user.events.build

    authorize @event
  end

  def create
    @event = current_user.events.build(event_params)
    authorize @event

    if @event.save
      redirect_to @event, notice: I18n.t('controllers.events.created')
    else
      render :new
    end
  end

  def update
    authorize @event

    if @event.update(event_params)
      redirect_to @event, notice: I18n.t('controllers.events.updated')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @event

    @event.destroy
    redirect_to events_url, status: :see_other, notice: I18n.t('controllers.events.destroyed')
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event)
          .permit(:title, :address, :datetime, :description, :pincode, :photo)
  end

  def render_password_form
    flash.now[:alert] = I18n.t('controllers.events.wrong_pincode') if params[:pincode].present?
    render 'password_form'
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<div class="col-sm-6 col-md-4">
  <div class="thumbnail">

    <%= content_tag 'div', '', class: 'event-background',
                    style: "background-image: url(#{asset_path('event_thumb.jpg')})" %>

    <div class="thumbnail-inner event-info-inner">
      <div class="caption">
        <div class="event-description">
          <h3><%= link_to event.title, event_path(event) %></h3>
          <h3><small><%= l event.datetime, format: :short %></small></h3>
          <div class="buffer-both"><%= event.address %></div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<%= form_for @event, data: { turbo: false } do |f| %>
  <%= render partial: 'partials/form_errors', locals: {model: @event} %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :datetime %>
    <p><%= f.datetime_select :datetime, class: 'form-control' %></p>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :pincode %>
    <%= f.text_field :pincode, class: 'form-control' %>
  </div>

  <div class="actions my-4">
    <%= f.submit t('views.events.form.save'), class: 'btn btn-primary' %>
    <%= t('views.events.form.or') %> <%= link_to t('views.events.form.back'), :back %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1 class="my-3"><%= t('views.events.edit.editing') %></h1>

<%= render 'form' %>

<%= link_to t('views.events.edit.links.show_event'), @event %> |
<%= link_to t('views.events.edit.links.back_to_events'), events_path %>

app/views/events/index.html.erb
<h1 class="my-4"><%= t('views.events.index.events') %></h1>

<div class="buffer-both">
  <%= link_to t('views.events.index.new_events'), new_event_path, class: 'btn btn-success' %>
</div>

<div class="row buffer-bottom">
  <%= render partial: 'events/event', collection: @events %>
</div>

app/views/events/new.html.erb
<h1 class="my-3"><%= t('views.events.index.new_events') %></h1>

<div class="row">
  <div class="col-md-6 buffer-top">
    <%= render 'form' %>
  </div>
</div>

app/views/events/password_form.html.erb
<h1><%= t('views.events.password.access_pincode_only') %></h1>

<%= form_tag('', method: 'post') do |f| %>
  <div class="form-group">
    <%= label t('views.events.password.pincode'), :pincode %>
    <%= text_field_tag :pincode, params[:pincode], class: 'form-control' %>
  </div>

  <div class="actions">
    <%= submit_tag %>
  </div>
<% end %>

<%= link_to t('views.events.password.back_to_events'), events_path %>

app/views/events/show.html.erb
<div class="event">
  <div class="event-info row">
    <div class="col-md-12">
      <%# Выводим произвольную фотку в качестве фона для шапки события %>
      <%= content_tag 'div', '', class: 'event-background',
                      style: "background-image: url(#{asset_path('event.jpg')})" %>

      <div class="event-info-inner row">
        <div class="col-md-6">
          <div class="event-description">
            <h1><%= @event.title %></h1>
            <h3><%= l @event.datetime, format: :short %></h3>
            <h3>
              <small><%= link_to @event.address,
                                 "https://yandex.ru/maps/?text=#{@event.address}" %></small>
            </h3>
            <p><%= @event.description %></p>
          </div>

          <div id="map"
               data-address="<%= @event.address %>"
               style="width: 100%;
                 height: 400px">
          </div>

          <% if current_user_can_edit?(@event) %>
            <div class="buffer-both">
              <%= link_to t('views.events.show.edit'), edit_event_path(@event),
                          class: 'btn btn-primary' %>
              <%= button_to t('views.events.show.delete'), @event,
                            method: :delete,
                            form: { data: { turbo_confirm: t('views.events.show.deletion_confirmation') } },
                            class: 'btn btn-danger'
              %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="event-photos-gallery d-flex flex-wrap">
    <%= render partial: 'photos/photo', collection: @event.photos.except(@new_photo) %>
  </div>

  <% if user_signed_in? %>
    <div class="event-photo-form">
      <%= render partial: 'photos/form', locals: { photo: @new_photo || @event.photos.build } %>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-8">
      <div class="event-comments buffer-top">
        <%= render partial: 'comments/form',
                   locals: {comment: @new_comment || @event.comments.build} %>

        <div class="buffer-both">
          <%= render partial: 'comments/comment',
                     collection: @event.comments.except(@new_comment) %>
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="event-owner">
        <h4>Зовет:</h4>
        <p><%= render partial: 'users/user', object: @event.user %></p>
      </div>
      <div class="event-subscriptions">
        <h4><%= t('views.events.show.attendees')%></h4>
        <div>
          <p>
            <%= render partial: 'subscriptions/subscription',
                       collection: @event.subscriptions.except(@new_subscription) %>
          </p>
        </div>
      </div>
      <% if @event.user != current_user %>
        <div class="event-subscription-form">
          <h4><%= t('views.events.show.subscription')%></h4>
          <div>
            <%= render partial: 'subscriptions/form', locals: {
              subscription: @new_subscription || @event.subscriptions.build
            } %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>