config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "events#index"

  resources :events do
    resources :comments, only: %i[create destroy]
    resources :subscriptions, only: %i[create destroy]
    resources :photos, only: %i[create destroy]
    put :update_photo, on: :member
    post :show, on: :member
  end

  resources :users, only: %i[show edit update]
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :event
  belongs_to :user

  has_one_attached :attached_photo, dependent: :purge do |attachable|
    attachable.variant :thumb, resize_to_limit: [200, 200]
  end

  validates :event, presence: true
  validates :user, presence: true
  validates :attached_photo, presence: true

  scope :persisted, -> { where.not(id: nil) }
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!, on: [:create]
  before_action :set_event, only: %i[create destroy]
  before_action :set_photo, only: [:destroy]

  def create
    @new_photo = @event.photos.build(photo_params)
    @new_photo.user = current_user
    if @new_photo.save
      notify_subscribers(@event, @new_photo)
      redirect_to @event, notice: I18n.t('controllers.photos.created')
    else
      render 'events/show', alert: I18n.t('controllers.photos.error')
    end
  end

  def destroy
    message = { notice: I18n.t('controllers.photos.destroyed') }

    @photo.destroy

    redirect_to @event, message
  end

  private

  def set_event
    @event = Event.find(params[:event_id])
  end

  def set_photo
    @photo = @event.photos.find(params[:id])
  end

  def photo_params
    params.require(:photo).permit(:attached_photo)
  end

  def notify_subscribers(event, photo)
    all_emails = (event.subscriptions.map(&:user_email) + [event.user.email] - [photo.user&.email]).uniq

    all_emails.each do |email|
      EventMailer.photo(photo, email).deliver_now
    end
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_footer.html.erb
<%= render partial: 'users/info', locals: { user: photo.user } %>
<% if current_user_can_edit?(photo) %>
  <%= button_to '', event_photo_path(photo.event, photo),
                method: :delete,
                form: { data: { turbo_confirm: t('views.photos.footer.confirm_deletion') } },
                class: 'btn bi bi-trash2',
                form_class: 'd-inline',
                style: 'color: white'
  %>
<% end %>

app/views/photos/_form.html.erb
<%= form_with model:[@event, photo], html: { multipart: true }, data: { turbo: false } do |f| %>
  <%= render partial: 'partials/form_errors', locals: {model: photo} %>

  <div class="form-group">
    <%= f.label :photo %>
    <%= f.file_field :attached_photo, direct_upload: true, class: 'form-control' %>
  </div>
  <div class="actions my-4">
    <%= f.submit t('views.events.form.save'), class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/photos/_photo.html.erb
<% image_title = "#{render partial: 'photos/footer', locals: { photo: photo }}"%>

<%= link_to image_tag(photo.attached_photo.variant(:thumb), class: 'img-fluid'),
            photo.attached_photo.url,
            data: { lightbox: 'lightbox-photos', title: image_title }
    %>